(()=>{
  const API='/api/market-events'; let pin='',events=[],meta={};
  const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const statusText=e=>e.eventOnly?'Event time only':e.actual?'Actual received':e.officialAuto?(e.previousStatus==='ready'?'Official connected':'Awaiting official sync'):'Manual / fallback';
  function visibleEvents(){const q=$('#searchInput').value.trim().toLowerCase(),f=$('#filterSelect').value,now=Date.now();return events.map((e,i)=>({e,i})).filter(({e})=>{
    const text=`${e.name} ${e.nameZh} ${e.type}`.toLowerCase();if(q&&!text.includes(q))return false;
    if(f==='waiting'&&!(e.previousStatus==='awaiting_official'||(e.released&&!e.actual&&!e.eventOnly)))return false;
    if(f==='missingForecast'&&(e.forecast||e.eventOnly))return false;
    if(f==='released'&&new Date(e.datetime).getTime()>now)return false;
    if(f==='upcoming'&&new Date(e.datetime).getTime()<=now)return false;return true;
  });}
  function render(){
    const rows=visibleEvents(); $('#adminEvents').innerHTML=rows.length?rows.map(({e,i})=>{
      const waiting=e.previousStatus==='awaiting_official'||(e.released&&!e.actual&&!e.eventOnly); const eventOnly=e.eventOnly;
      const last=e.lastRelease||{};
      const historyRows=(e.history||[]).slice(0,10).map((h,n)=>`<div class="history-row"><span class="history-num">${n+1}</span><label class="label">Period<input class="input locked" readonly value="${esc(h.period||'—')}"></label><label class="label">Actual<input class="input locked" readonly value="${esc(h.actual||'—')}"></label><label class="label">Previous<input class="input locked" readonly value="${esc(h.previous||'—')}"></label><label class="label">Forecast（你填写）<input class="input" data-history-period="${esc(h.period||'')}" value="${esc(h.forecast||'')}" placeholder="填写该期 Forecast"></label></div>`).join('');
      const fields=eventOnly?`<label class="label">Malaysia date & time<input class="input" data-k="datetime" type="datetime-local" value="${esc((e.datetime||'').slice(0,16))}"></label><label class="label">Status<input class="input locked" readonly value="${esc(e.status||'Scheduled')}"></label>`:`<label class="label">Malaysia date & time<input class="input" data-k="datetime" type="datetime-local" value="${esc((e.datetime||'').slice(0,16))}"></label><label class="label">Next Forecast<input class="input" data-k="forecast" value="${esc(e.forecast)}" placeholder="下一次，例如 2.8% / 180K"></label><label class="label">Previous (Automatic)<input class="input locked" readonly value="${esc(e.previous||'—')}"></label><label class="label">Actual (Official)<input class="input locked" readonly value="${esc(e.actual||'—')}"></label><div class="history-wrap"><b>最近 10 次 Last Releases</b>${historyRows||'<p class="admin-note">官方历史记录同步后会显示在这里。</p>'}</div>`;
      return `<article class="event ${waiting?'waiting':'ready'}" data-i="${i}"><div class="event-head"><div><strong>${esc(e.name)}</strong><span class="zh">${esc(e.nameZh||'')} · ${esc(e.releasePeriod||'')}</span></div><div class="badges"><span class="badge">${'★'.repeat(Number(e.impact)||4)}</span><span class="badge ${waiting?'warn':'ok'}">${esc(statusText(e))}</span></div></div><div class="grid">${fields}</div></article>`;
    }).join(''):'<p class="admin-note">没有符合筛选条件的新闻。</p>';
    updateStats();
  }
  function updateStats(){const waiting=events.filter(e=>e.previousStatus==='awaiting_official'||(e.released&&!e.actual&&!e.eventOnly)).length;$('#totalCount').textContent=events.length;$('#readyCount').textContent=events.filter(e=>e.officialAuto&&e.previousStatus==='ready').length;$('#waitingCount').textContent=waiting;$('#forecastCount').textContent=events.filter(e=>e.forecast).length;
    const s=meta.officialSources||{};const items=[['Static Cache',s.staticCache],['BLS',s.bls],['FRED',s.fred],['Department of Labor',s.dol],['BEA',s.bea],['Federal Reserve',s.federalReserve],['Cloudflare KV',meta.kvConfigured]];$('#sourceGrid').innerHTML=items.map(([n,v])=>`<div class="source ${v?'ok':'bad'}"><b>${v?'● Connected':'● Not connected'}</b>${n}</div>`).join('');$('#syncLine').textContent=`页面更新：${fmt(meta.updatedAt)} · 官方数据更新：${fmt(meta.officialUpdatedAt)}${meta.officialError?' · Error: '+meta.officialError:''}`;}
  const fmt=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur',hour12:false}):'尚无记录';
  function collect(){document.querySelectorAll('.event').forEach(card=>{const i=+card.dataset.i;card.querySelectorAll('[data-k]').forEach(input=>{if(input.disabled)return;let v=input.value.trim();const key=input.dataset.k;if(key==='datetime'&&v&&!/[zZ]|[+-]\d\d:\d\d$/.test(v))v+=':00+08:00';events[i][key]=v;});events[i].releaseForecasts=events[i].releaseForecasts||{};card.querySelectorAll('[data-history-period]').forEach(input=>{const period=input.dataset.historyPeriod;const value=input.value.trim();if(period){if(value)events[i].releaseForecasts[period]=value;else delete events[i].releaseForecasts[period];}});});}
  async function load(){const r=await fetch(API,{headers:{'x-admin-pin':pin},cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'无法打开后台');events=d.events||[];meta=d;render();}
  async function unlock(){pin=$('#adminPin').value.trim();$('#loginStatus').textContent='检查中…';try{await load();sessionStorage.setItem('ghAdminPin',pin);$('#loginPanel').hidden=true;$('#dashboard').hidden=false;$('#loginStatus').textContent='';}catch(e){$('#loginStatus').textContent=e.message;}}
  $('#unlockAdmin').addEventListener('click',unlock);$('#adminPin').addEventListener('keydown',e=>{if(e.key==='Enter')unlock();});$('#adminPin').value=sessionStorage.getItem('ghAdminPin')||'';
  $('#searchInput').addEventListener('input',render);$('#filterSelect').addEventListener('change',render);$('#refreshData').addEventListener('click',async()=>{collect();$('#saveStatus').textContent='重新读取中…';try{await load();$('#saveStatus').textContent='已读取最新数据。';}catch(e){$('#saveStatus').textContent=e.message;}});
  $('#saveEvents').addEventListener('click',async()=>{collect();const st=$('#saveStatus'),btn=$('#saveEvents');st.textContent='保存中…';btn.disabled=true;try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','x-admin-pin':pin},body:JSON.stringify({events})}),d=await r.json();if(!r.ok)throw new Error(d.error||'保存失败');st.textContent=`已保存 ${d.count} 项。Admin 与 Calendar 已使用同一份新闻清单，最近 10 次 Last Release Forecast 会立即同步。`;await load();}catch(e){st.textContent=e.message;}finally{btn.disabled=false;}});
  $('#logoutAdmin').addEventListener('click',()=>{sessionStorage.removeItem('ghAdminPin');location.reload();});
})();
